services:
  backend:
    image: sante-backend:latest
    container_name: sante-backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ENV
      - ORIGIN
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_SECRET_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_BUCKET_NAME
      - AWS_SES_SENDER_EMAIL
      - AWS_SES_ACCESS_KEY_ID
      - AWS_SES_ACCESS_KEY
      - FIREBASE_PRIVATE_KEY_ID
      - FIREBASE_PRIVATE_KEY_ID_PRETZLEY_MEMBERSHIP
      - SANTE_GOOGLE_AUTH_CLIENT_ID
    networks:
      - shared
  redis:
    image: redis
    container_name: redis
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared-network
    # external: true
